/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.39
 * Generated at: 2015-08-25 06:00:07 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fsecurity_005fauthentication_0026_005fproperty_005fnobody;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fsecurity_005fauthentication_0026_005fproperty_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fsecurity_005fauthentication_0026_005fproperty_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');

	response.setHeader("Content-Type", "text/html");
	//no cache
    response.setHeader("Pragma", "No-cache");
    response.setHeader("Cache-Control", "no-cache");
    response.setDateHeader("Expires", 0);

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"utf-8\">\n");
      out.write("    <link href=\"./css/modern.css\" rel=\"stylesheet\">\n");
      out.write("    <link href=\"./css/modern-responsive.css\" rel=\"stylesheet\">\n");
      out.write("    <link href=\"./css/droptiles.css\" rel=\"stylesheet\">\n");
      out.write("\t<link rel=\"stylesheet\" href=\"./themes/sunny/easyui.css\">\n");
      out.write("\t<link rel=\"stylesheet\" href=\"./themes/icon.css\">\n");
      out.write("\t<link rel=\"stylesheet\" href=\"./css/toolbar.css\">\n");
      out.write("\t<link rel=\"stylesheet\" href=\"./css/logout.css\"/>\n");
      out.write("\t<script src=\"./js/jquery-1.8.2.min.js\"></script>\n");
      out.write("\t<script src=\"./js/jquery.easyui.min.js\"></script>\n");
      out.write("\t<!-- <script src=\"./js/dropdown.js\"></script> -->\n");
      out.write("    <script src=\"./js/tiles.js\"></script>\n");
      out.write("    <script src=\"./js/moduleWindow.js\"></script>\n");
      out.write("\t<!-- <script src=\"/menus.js\"></script> -->\n");
      out.write("\t\n");
      out.write("\t<script src=\"./js/jquery.simplemodal.js\"></script>\n");
      out.write("\t<script src=\"./js/overlay.js\"></script>\n");
      out.write("\t<script src=\"./js/jquery.json-2.2.js\"></script>\n");
      out.write("\n");
      out.write("    \n");
      out.write("    <title>新农合证卡管理系统</title>\n");
      out.write("\n");
      out.write("    <style>\n");
      out.write("        body {\n");
      out.write("            background-image:url(");
      out.print(request.getContextPath());
      out.write("/images/InBloom.jpg)  \n");
      out.write("        }\n");
      out.write("\t\tdiv[data-liffect=\"zoomIn\"] > div {\n");
      out.write("\t\t\topacity: 0;\n");
      out.write("\t\t\tposition: relative;\n");
      out.write("\t\t\tanimation: zoomIn 1000ms ease both;\n");
      out.write("\t\t\tanimation-play-state: paused;\n");
      out.write("\t\t}\n");
      out.write("\n");
      out.write("\t\tdiv[data-liffect=\"zoomIn\"].play > div {\n");
      out.write("\t\t\tanimation-play-state: running;\n");
      out.write("\t\t}\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t@keyframes zoomIn {\n");
      out.write("\t\t\t0% { opacity: 0; transform: scale(1.5); }\n");
      out.write("\t\t\t100% { opacity: 1; transform: scale(1); }\n");
      out.write("\t\t}\n");
      out.write("    </style>\n");
      out.write("\n");
      out.write("    <script>\n");
      out.write("\n");
      out.write("$(function(){\n");
      out.write("\t\tvar agentScreen = [{\"scWidth\":\"1920\",\"scHeight\":\"1080\",\"uiReigon1Width\":\"1100px\",\"uiReigon2Width\":\"562px\",\"tileSize\":\"100\"},{\"scWidth\":\"1680\",\"scHeight\":\"1050\",\"uiReigon1Width\":\"1000px\",\"uiReigon2Width\":\"462px\",\"tileSize\":\"100\"},{\"scWidth\":\"1600\",\"scHeight\":\"900\",\"uiReigon1Width\":\"900px\",\"uiReigon2Width\":\"562px\",\"tileSize\":\"100\"},{\"scWidth\":\"1440\",\"scHeight\":\"900\",\"uiReigon1Width\":\"750px\",\"uiReigon2Width\":\"562px\",\"tileSize\":\"100\"},{\"scWidth\":\"1400\",\"scHeight\":\"1050\",\"uiReigon1Width\":\"700px\",\"uiReigon2Width\":\"562px\",\"tileSize\":\"100\"},{\"scWidth\":\"1366\",\"scHeight\":\"768\",\"uiReigon1Width\":\"802px\",\"uiReigon2Width\":\"362px\",\"tileSize\":\"100\"},{\"scWidth\":\"1360\",\"scHeight\":\"768\",\"uiReigon1Width\":\"802px\",\"uiReigon2Width\":\"362px\",\"tileSize\":\"100\"},{\"scWidth\":\"1280\",\"scHeight\":\"768\",\"uiReigon1Width\":\"752px\",\"uiReigon2Width\":\"362px\",\"tileSize\":\"100\"},{\"scWidth\":\"1280\",\"scHeight\":\"720\",\"uiReigon1Width\":\"762px\",\"uiReigon2Width\":\"362px\",\"tileSize\":\"100\"},{\"scWidth\":\"1280\",\"scHeight\":\"600\",\"uiReigon1Width\":\"762px\",\"uiReigon2Width\":\"362px\",\"tileSize\":\"80\"},{\"scWidth\":\"1024\",\"scHeight\":\"768\",\"uiReigon1Width\":\"552px\",\"uiReigon2Width\":\"362px\",\"tileSize\":\"80\"}];\n");
      out.write("\t\tvar screenWidth = screen.width;\n");
      out.write("\t\tvar screenHeight = screen.height;\n");
      out.write("\t\t//alert(screenWidth);\n");
      out.write("\t\t//alert(screenHeight);\n");
      out.write("\t\tvar uiReigon1Width,uiReigon2Width,tileSize;\n");
      out.write("\t\tfor(var i in agentScreen){\n");
      out.write("\t\t\tif(screenWidth == agentScreen[i].scWidth && screenHeight == agentScreen[i].scHeight){\n");
      out.write("\t\t\t\tuiReigon1Width = agentScreen[i].uiReigon1Width;\n");
      out.write("\t\t\t\tuiReigon2Width = agentScreen[i].uiReigon2Width;\n");
      out.write("\t\t\t\ttileSize = agentScreen[i].tileSize;\n");
      out.write("\t\t\t}\n");
      out.write("\t\t\t//alert(agentScreen[i].scWidth + \"---\" + agentScreen[i].scHeight);\n");
      out.write("\t\t}\n");
      out.write("\t\t//alert(uiReigon1Width + \"---\" + uiReigon2Width + \"---\" + tileSize);\n");
      out.write("\t\t$(\"div.tile-group:first\").width(uiReigon1Width);\n");
      out.write("\t\t$(\"div.tile-group:last\").width(uiReigon2Width);\n");
      out.write("\t\t$.ajax({\n");
      out.write("\t\t\t   type: \"get\",\n");
      out.write("\t\t\t   async:false,\n");
      out.write("\t\t\t   url: \"");
      out.print(request.getContextPath());
      out.write("/FuncMenuServlet/getTodoMenu.do\",\n");
      out.write("\t\t\t   data: {},\n");
      out.write("\t\t\t   dataType: \"json\",\n");
      out.write("\t\t\t   success: function(jsondata){\n");
      out.write("\t\t\t       window.todo_menu = {};\n");
      out.write("\t\t\t       for(var i = 0 ;i <jsondata.length;i++){\n");
      out.write("\t\t\t\t    window.todo_menu[jsondata[i].resource_id] = jsondata[i];\n");
      out.write("\t\t\t       }\n");
      out.write("\t\t\t   }\n");
      out.write("\t\t});\n");
      out.write("\t\t$.ajax({\n");
      out.write("\t\t\t   type: \"get\",\n");
      out.write("\t\t\t   url: \"");
      out.print(request.getContextPath());
      out.write("/FuncMenuServlet/getFuncMenu.do\",\n");
      out.write("\t\t\t   data: {},\n");
      out.write("\t\t\t   dataType: \"json\",\n");
      out.write("\t\t\t   success: function(jsondata){\n");
      out.write("\t\t\t\t   //alert(jsondata.funcMenuJson);\n");
      out.write("\t\t\t\t   //var t = '[{\"a\":\"1\",\"b\":\"2\"},{\"ca\":\"3\",\"d\":\"4\"}]';\n");
      out.write("\t\t\t\t\t\t// '[{\"name\":\"John\"},{\"name\":\"John\"}]'\n");
      out.write("\t\t\t\t   //alert(t.length);\n");
      out.write("\t\t\t\t   //alert(jQuery.parseJSON(t));\n");
      out.write("\t\t\t\t   var z = '[{\"selfId\":\"mainId1\",\"parentId\":\"#mainFuncId\",\"isDouble\":\"no\",\"bgColor\":\"bg-color-red\",\"tileType\":\"icon\",\"imgSrc\":\"");
      out.print(request.getContextPath());
      out.write("/images/Calendar.png\",\"brandName\":\"电子地图\",\"brandCount\":\"\",\"badgeColor\":\"\",\"tileHtml\":\"\",\"submenus\":[{\"selfId\":\"\",\"parentId\":\"#subFuncId\",\"isDouble\":\"no\",\"bgColor\":\"bg-color-pinkDark\",\"tileType\":\"icon\",\"imgSrc\":\"");
      out.print(request.getContextPath());
      out.write("/images/MB_0015_currency-e-j.png\",\"brandName\":\"地块税收监控\",\"brandCount\":\"\",\"badgeColor\":\"\",\"tileHtml\":\"\",\"menuIcon\":\"");
      out.print(request.getContextPath());
      out.write("/images/MB_0015_currency-e-j.png\",\"menuUrl\":\"url:/map/basic2.html\"},{\"selfId\":\"\",\"parentId\":\"#subFuncId\",\"isDouble\":\"no\",\"bgColor\":\"bg-color-pinkDark\",\"tileType\":\"icon\",\"imgSrc\":\"");
      out.print(request.getContextPath());
      out.write("/images/MB_0012_COMPAS2.png\",\"brandName\":\"土地房产监控\",\"brandCount\":\"\",\"badgeColor\":\"\",\"tileHtml\":\"\",\"menuIcon\":\"");
      out.print(request.getContextPath());
      out.write("/images/MB_0012_COMPAS2.png\",\"menuUrl\":\"url:/map/basic3.html\"}]}]';\n");
      out.write("\t\t\t\t\t//alert(jQuery.parseJSON(z));\n");
      out.write("\t\t\t\t\tregex = new RegExp(\"null\",\"g\");  \n");
      out.write("\t\t\t\t\t//$inputValue = $inputValue.replace(regex, \"\");  \n");
      out.write("\t\t\t\t\tvar menus = jQuery.parseJSON(jsondata.funcMenuJson.replace(regex, \"\"));\n");
      out.write("\t\t\t\t\t//alert(menus);\n");
      out.write("\t\t\t\t\tvar localObj = window.location;\n");
      out.write("\t\t\t\t\tvar contextPath = \"/\"+localObj.pathname.split(\"/\")[1]; \n");
      out.write("\t\t\t\t\tfor (var i in menus) {\n");
      out.write("\t\t\t\t\t\tnew tiles(menus[i].selfId,menus[i].parentId,menus[i].isDouble,menus[i].bgColor,menus[i].tileType,menus[i].imgSrc,menus[i].brandName,menus[i].brandCount,menus[i].badgeColor,menus[i].tileHtml,menus[i].todoUrl,menus[i].todoMenuid).bind('click',{index: i},  function(event){\n");
      out.write("\t\t\t\t\t\t\tvar brothernodes = $(this).siblings();\n");
      out.write("\t\t\t\t\t\t\tfor(var j = 0;j < brothernodes.length;j++){\n");
      out.write("\t\t\t\t\t\t\t\t$(brothernodes[j]).fadeTo('fast',0.35);\n");
      out.write("\t\t\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t\t\t $(this).fadeTo('fast',1);\n");
      out.write("\t\t\t\t\t\t\tvar i = event.data.index;\n");
      out.write("\t\t\t\t\t\t\tvar submenus = menus[event.data.index].submenus;\n");
      out.write("\t\t\t\t\t\t\t$('#subFuncId').empty();\n");
      out.write("\t\t\t\t\t\t\tfor (var j in submenus) {\n");
      out.write("\t\t\t\t\t\t\t\tnew tiles(submenus[j].selfId,submenus[j].parentId,submenus[j].isDouble,submenus[j].bgColor,submenus[j].tileType,submenus[j].imgSrc,submenus[j].brandName,submenus[j].brandCount,submenus[j].badgeColor,submenus[j].tileHtml,submenus[j].todoUrl,submenus[j].todoMenuid).bind('click',{index: j},  function(event){\n");
      out.write("\t\t\t\t\t\t\t\t\tvar j = event.data.index;\n");
      out.write("\t\t\t\t\t\t\t\t\tmoduleWindow.open({\n");
      out.write("\t\t\t\t\t\t\t\t\t\tid: \"module_\" + submenus[j].resource_id + \"_\" + \"Id\",\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttitle: submenus[j].brandName,\n");
      out.write("\t\t\t\t\t\t\t\t\t\twidth: 1200,\n");
      out.write("\t\t\t\t\t\t\t\t\t\theight: 580,\n");
      out.write("\t\t\t\t\t\t\t\t\t\ticon: submenus[j].menuIcon,\n");
      out.write("\t\t\t\t\t\t\t\t\t\tminimizable: true,\n");
      out.write("\t\t\t\t\t\t\t\t\t\tmaximized:true,\n");
      out.write("\t\t\t\t\t\t\t\t\t\t//data: {name: 'Tom', age: 18}, //传递给iframe的数据\n");
      out.write("\t\t\t\t\t\t\t\t\t\tcontent: submenus[j].menuUrl,\n");
      out.write("\t\t\t\t\t\t\t\t\t\tonLoad: function(dialog){\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tif(this.content && this.content.doInit){//判断弹出窗体iframe中的doInit方法是否存在\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tthis.content.doInit(dialog);//调用并将参数传入，此处当然也可以传入其他内容\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t\t\t\t\t\t},\n");
      out.write("\t\t\t\t\t\t\t\t\t\tonBeforeClose:function(dialog){\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tupdatenum();\n");
      out.write("\t\t\t\t\t\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t\t\t\t\t\t,buttons: []\n");
      out.write("\t\t\t\t\t\t\t\t\t\t//,buttons: [{\"text\":\"aaa\",handler:function(){}},{\"text\":\"bbb\",handler:function(){}}]\n");
      out.write("\t\t\t\t\t\t\t\t\t});\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t});\n");
      out.write("\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t$(\"div.tile-group:last > div\").width(tileSize+\"px\").height(tileSize+\"px\");\n");
      out.write("\t\t\t\t\t\t\t\t$('div.tile-group:last > div').each(function(i){\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t$(this).width(tileSize).width(tileSize+\"px\").height(tileSize+\"px\");\n");
      out.write("\t\t\t\t\t\t\t\t\t$(\"div[data-liffect]\").addClass(\"play\")\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t})\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t}\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t});\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t//alert($(\"div.tile-group:first > div\").length);\n");
      out.write("\t\t\t\t\t$('div.tile-group:first > div').each(function(i){\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t//alert($(this).attr(\"class\"));\n");
      out.write("\t\t\t\t\t\tif($(this).attr(\"class\").indexOf(\"double\") >= 0){\n");
      out.write("\t\t\t\t\t\t\t$(this).width((tileSize * 2 + 10)+\"px\").height(tileSize);\n");
      out.write("\t\t\t\t\t\t}else{\n");
      out.write("\t\t\t\t\t\t\t$(this).width(tileSize).height(tileSize);\n");
      out.write("\t\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t\t$(\"div[data-liffect]\").addClass(\"play\");\n");
      out.write("\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t})\n");
      out.write("\t\t\t\t\t\n");
      out.write("\n");
      out.write("\t           }\n");
      out.write("\t   });\n");
      out.write("\n");
      out.write("\t\t//var items=[];\n");
      out.write("\t\t//$(\"div.tile-group:first > div\").width(tileSize).height(tileSize);\n");
      out.write("\t\t\n");
      out.write("\n");
      out.write("\n");
      out.write("})\n");
      out.write("\n");
      out.write("\n");
      out.write("    </script>\n");
      out.write("</head>\n");
      out.write("<body class=\"modern-ui\" style=\"overflow:hidden\">\n");
      out.write("\n");
      out.write("\t\t<!-- 退出窗口的模态框 -->\n");
      out.write("\t\t<div id=\"overlay-modal-content\">\n");
      out.write("\t\t\t<!--<div id=\"overlay-modal-title\"></div>-->\n");
      out.write("\t\t\t<div class=\"close\"><a href=\"#\" class=\"simplemodal-close\">x</a></div>\n");
      out.write("\t\t\t<div id=\"overlay-modal-data\">\n");
      out.write("\t\t\t\t<form name=\"login-form\" class=\"login-form\" action=\"");
      out.print(request.getContextPath());
      out.write("/j_spring_security_logout\" method=\"post\">\n");
      out.write("\t\t\t\t\t<div class=\"header\">\n");
      out.write("\t\t\t\t\t\t<h1></h1>\n");
      out.write("\t\t\t\t\t\t<span><img src=\"");
      out.print(request.getContextPath());
      out.write("/images/109.png\"></span>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"content\">\n");
      out.write("\t\t\t\t\t\t<label class=\"label\">确实要退出系统吗?</label>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"footer\">\n");
      out.write("\t\t\t\t\t\t<input type=\"submit\" class=\"button\" value=\"退出系统\"/>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</form>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\n");
      out.write("        <div class=\"navbar\" >\n");
      out.write("            <div class=\"navbar-inner\">\n");
      out.write("\n");
      out.write("                    <div>\n");
      out.write("                        <ul class=\"nav\">\n");
      out.write("                            <li><a class=\"active\" href=\"#\">");
      if (_jspx_meth_security_005fauthentication_005f0(_jspx_page_context))
        return;
      out.write("</a></li>\n");
      out.write("\t\t\t\t\t\t\t<li><a class=\"active\" href=\"#\">");
      if (_jspx_meth_security_005fauthentication_005f1(_jspx_page_context))
        return;
      out.write("</a></li>\n");
      out.write("                            <li style=\"float:right;padding:0 0 5px 0\"><a class=\"active\" id=\"loginId1\">退出</a></li>\n");
      out.write("                        </ul>\n");
      out.write("                    </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("<div class=\"page secondary fixed-header\">\n");
      out.write("\n");
      out.write("\n");
      out.write("    <div class=\"page-region\">\n");
      out.write("        <div class=\"page-region-content tiles\">\n");
      out.write("            <div data-liffect=\"zoomIn\" class=\"tile-group\" id=\"mainFuncId\">\n");
      out.write("\n");
      out.write("\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("            <div data-liffect=\"zoomIn\" class=\"tile-group\" id=\"subFuncId\">\n");
      out.write("\n");
      out.write("\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</div>\n");
      out.write("<div id=\"box\"> \n");
      out.write("\n");
      out.write("</div>  \n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_security_005fauthentication_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  security:authentication
    org.springframework.security.taglibs.authz.AuthenticationTag _jspx_th_security_005fauthentication_005f0 = (org.springframework.security.taglibs.authz.AuthenticationTag) _005fjspx_005ftagPool_005fsecurity_005fauthentication_0026_005fproperty_005fnobody.get(org.springframework.security.taglibs.authz.AuthenticationTag.class);
    _jspx_th_security_005fauthentication_005f0.setPageContext(_jspx_page_context);
    _jspx_th_security_005fauthentication_005f0.setParent(null);
    // /main.jsp(213,59) name = property type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_security_005fauthentication_005f0.setProperty("principal.orgName");
    int _jspx_eval_security_005fauthentication_005f0 = _jspx_th_security_005fauthentication_005f0.doStartTag();
    if (_jspx_th_security_005fauthentication_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fsecurity_005fauthentication_0026_005fproperty_005fnobody.reuse(_jspx_th_security_005fauthentication_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fsecurity_005fauthentication_0026_005fproperty_005fnobody.reuse(_jspx_th_security_005fauthentication_005f0);
    return false;
  }

  private boolean _jspx_meth_security_005fauthentication_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  security:authentication
    org.springframework.security.taglibs.authz.AuthenticationTag _jspx_th_security_005fauthentication_005f1 = (org.springframework.security.taglibs.authz.AuthenticationTag) _005fjspx_005ftagPool_005fsecurity_005fauthentication_0026_005fproperty_005fnobody.get(org.springframework.security.taglibs.authz.AuthenticationTag.class);
    _jspx_th_security_005fauthentication_005f1.setPageContext(_jspx_page_context);
    _jspx_th_security_005fauthentication_005f1.setParent(null);
    // /main.jsp(214,38) name = property type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_security_005fauthentication_005f1.setProperty("principal.taxempname");
    int _jspx_eval_security_005fauthentication_005f1 = _jspx_th_security_005fauthentication_005f1.doStartTag();
    if (_jspx_th_security_005fauthentication_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fsecurity_005fauthentication_0026_005fproperty_005fnobody.reuse(_jspx_th_security_005fauthentication_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fsecurity_005fauthentication_0026_005fproperty_005fnobody.reuse(_jspx_th_security_005fauthentication_005f1);
    return false;
  }
}
